// Export all sections for easy importing
export { default as Hero } from './Hero'
export { default as TrustBar } from './TrustBar'
export { default as Problem } from './Problem'
export { default as Solution } from './Solution'
export { default as ModelesPreview } from './ModelesPreview'
export { default as WhyNotWix } from './WhyNotWix'
export { default as NotIncluded } from './NotIncluded'
export { default as PlanGratuit24h } from './PlanGratuit24h'
export { default as Process } from './Process'
export { default as Pricing } from './Pricing'
export { default as Reviews } from './Reviews'
export { default as FAQ } from './FAQ'
export { default as Compliance } from './Compliance'
